name: Create and Publish Docker Image for AS400 Java Log extractor
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      tag_message:
        required: true
        type: string
    secrets:
      REGISTRY_KEY:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: "Print tag"
        run: echo "Creating image with tag ${{env.TAG}}"

      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: |
          echo "Building jar in PROD environment"
          mvn -B -Pprod clean compile assembly:single --file pom.xml -s settings.xml
        env:
          MAVEN_TK: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: "Print secret"
        run: echo "${{secrets.REGISTRY_KEY}}"

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: utmstack.azurecr.io
          username: github
          password: ${{secrets.REGISTRY_KEY}}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: /home/runner/work/UTMStackDatasourceAS400/UTMStackDatasourceAS400/
          push: true
          tags: utmstack.azurecr.io/${{inputs.image_name}}:${{inputs.environment}}_${{ env.TAG }},utmstack.azurecr.io/${{inputs.image_name}}:${{inputs.environment}}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{inputs.environment}}_${{ env.TAG }}"
          message: ${{inputs.tag_message}}
