name: Java Log extractor for AS400
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  docker-as400-java:
    uses: ./.github/workflows/build-image-java.yml
    with:
      image_name: ibmas
      environment: prod
      branch: main
